"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import type { Competition } from "@/types";
import { formatRaceCell, getDiscardedRaceNumbers, raceNumbers, rankedAthletes } from "@/lib/scoring";

function exportRows(competition: Competition) {
  const races = raceNumbers(competition.raceCount);
  return rankedAthletes(competition.athletes, competition.raceCount).map((athlete) => {
    const discarded = getDiscardedRaceNumbers(athlete, competition.raceCount);
    return {
      Rank: athlete.rank,
      "Sail Number": athlete.sailNumber,
      Flag: athlete.flag,
      Nationality: athlete.nationality,
      "First Name": athlete.firstName,
      "Last Name": athlete.lastName,
      Club: athlete.clubName,
      "Boat Class": athlete.boatClass,
      ...Object.fromEntries(races.map((raceNumber) => [`Race ${raceNumber}`, formatRaceCell(athlete.results[raceNumber], discarded.has(raceNumber))])),
      Total: athlete.total,
      Discard: athlete.discard ?? 0,
      Net: athlete.net,
      "Final Rank": athlete.rank,
    };
  });
}

export function downloadCsv(competition: Competition) {
  const rows = exportRows(competition);
  const headers = Object.keys(rows[0] ?? { Rank: "", "Sail Number": "", Total: "", Discard: "", Net: "", "Final Rank": "" });
  const csv = [
    headers.join(","),
    ...rows.map((row) => headers.map((header) => JSON.stringify(String(row[header as keyof typeof row] ?? ""))).join(",")),
  ].join("\n");
  downloadBlob(csv, `${competition.name}-results.csv`, "text/csv;charset=utf-8;");
}

export function downloadExcel(competition: Competition) {
  const worksheet = XLSX.utils.json_to_sheet(exportRows(competition));
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Results");
  XLSX.writeFile(workbook, `${competition.name}-results.xlsx`);
}

export function downloadPdf(competition: Competition) {
  const doc = new jsPDF({ orientation: "landscape" });
  const races = raceNumbers(competition.raceCount);

  addLogo(doc, competition.clubLogo, 14, 10);
  addLogo(doc, competition.competitionLogo, 265, 10);

  doc.setFontSize(18);
  doc.text(competition.name, 14, 38);
  doc.setFontSize(10);
  doc.text(`Club: ${competition.clubName}`, 14, 46);
  doc.text(`Location: ${competition.location}`, 14, 52);
  doc.text(`Date: ${new Date(competition.date).toLocaleDateString()}`, 14, 58);
  doc.text(`Boat class: ${competition.boatClass}`, 14, 64);
  doc.text(`Number of races: ${competition.raceCount}`, 14, 70);

  autoTable(doc, {
    startY: 78,
    head: [["Rank", "Sail", "Flag", "Athlete", "Nationality", ...races.map((race) => `R${race}`), "Total", "Discard", "Net", "Final"]],
    body: rankedAthletes(competition.athletes, competition.raceCount).map((athlete) => {
      const discarded = getDiscardedRaceNumbers(athlete, competition.raceCount);
      return [
        athlete.rank,
        athlete.sailNumber,
        athlete.flag,
        `${athlete.firstName} ${athlete.lastName}`,
        athlete.nationality,
        ...races.map((raceNumber) => formatRaceCell(athlete.results[raceNumber], discarded.has(raceNumber))),
        athlete.total,
        athlete.discard ?? 0,
        athlete.net,
        athlete.rank,
      ];
    }),
    styles: { fontSize: 7, cellPadding: 1.8 },
    headStyles: { fillColor: [3, 105, 161] },
  });

  doc.setFontSize(9);
  doc.text("Generated by raceSail", 14, 200);
  doc.text("flooter creat by Mouadmouasseif : mouadmouasseif.vercel.app", 110, 200);
  doc.save(`${competition.name}-results.pdf`);
}

function addLogo(doc: jsPDF, logo: string | undefined, x: number, y: number) {
  if (!logo) return;
  try {
    const format = logo.includes("image/png") ? "PNG" : "JPEG";
    doc.addImage(logo, format, x, y, 18, 18);
  } catch {
    // Ignore invalid local images so exports never fail because of a logo.
  }
}

function downloadBlob(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = filename;
  link.click();
  URL.revokeObjectURL(link.href);
}
